name: Update Lines Across All Repos

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * 0"     # weekly
  workflow_dispatch:

env:
  OWNER: ${{ github.repository_owner }}
  # Add all identities you commit with, separated by |
  AUTHOR_PATTERNS: 'chucacabrawow@gmail.com|Glenn|chucacabrawow'
  VISIBILITY: public   # change to "all" if you later use a PAT and want private repos

jobs:
  total:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure README block exists
        shell: bash
        run: |
          if [ ! -f README.md ]; then
            echo "# Hi, I'm $OWNER 👋" > README.md
            echo "" >> README.md
          fi
          if ! grep -q "<!-- ALL-REPOS-START -->" README.md; then
            printf "\n### 📊 Lines of code across all repos\n<!-- ALL-REPOS-START -->\n_updating..._\n<!-- ALL-REPOS-END -->\n" >> README.md
          fi

      - name: Auth for gh (GITHUB_TOKEN, public repos)
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: gh auth status || true

      - name: List repos (include forks)
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          set -e
          # list ALL public repos (forks inc
