name: Update Lines Across All Repos

permissions:
  contents: write   # allow pushing README updates

on:
  schedule:
    - cron: "0 0 * * 0"   # weekly
  workflow_dispatch:

env:
  OWNER: ${{ github.repository_owner }}
  # Your identities (from the debug)
  AUTHOR_REGEX: '(?i)chucacabrawow@gmail\.com|glenn|chucacabrawow'
  # public = only public repos (default token OK)
  # all    = public + private (needs PAT secret REPOS_TOKEN)
  VISIBILITY: public

jobs:
  total:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure README block exists
        shell: bash
        run: |
          if [ ! -f README.md ]; then
            echo "# Hi, I'm $OWNER 👋" > README.md
            echo "" >> README.md
          fi
          if ! grep -q "<!-- ALL-REPOS-START -->" README.md; then
            printf "\n### 📊 Lines of code across all repos\n<!-- ALL-REPOS-START -->\n_updating..._\n<!-- ALL-REPOS-END -->\n" >> README.md
          fi

      - name: Auth for gh
        env:
          GH_TOKEN: ${{ secrets.REPOS_TOKEN || github.token
